version: "2" # Compose version used
services:    # All services are inputed in below
  # nginx node
  nginx:
    # Build based on a Dockerfile in /nginx directory
    build:
      context: ./nginx
    # Map port 80 container to port on 8400
    ports: 
      - "8400"
    # Mapping directory of container in /var/www to directory /www on laptop
    volumes:
      - ./www:/var/www
      - ./var/log/nginx:/var/log/nginx
    # Connecting nginx container with fpm container
    links:
      - fpm
      - memcached:memcached
    environment:
      - VIRTUAL_HOST=${HOST}

  # fpm node
  fpm:
    # Build based on a Dockerfile in /fpm directory
    build: 
      context: ./fpm
    # Mapping directory of container in /var/www to directory /www on laptop
    volumes:
      - ./www:/var/www
    # Mapping port 9000 container to port 9000 on laptop
    expose: 
      - "9000"
    # Connecting fpm container with db & memcached containers
    links:
      - ${DB_HOST}
      - memcached:memcached
    # Set variable
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_DATABASE=${DB_NAME}"

  # DB node
  db:
    # Build image directly from docker hub (mariadb)
    image: mariadb
    # Mapping port 3306 container to port 3306 on your machine
    expose:
      - "3306"
    # Set variable
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    # Mapping directory on container to database on laptop
    volumes:
      - ./var/lib/mariadb:/var/lib/mysql

  # memcached node
  memcached:
    # Build image directly from memcached (docker hub)
    image: memcached
    # Mapping port 11211 container to port 11211 on laptop
    expose:
      - "11211"
    environment:
      - MEMCACHED_MEMORY_LIMIT=128

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
