version: "3" 
services:
  mariadb:
    image: mariadb:10.1.32
    container_name: mariadb
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./var/lib/mariadb:/var/lib/mysql
  memcached:
    image: memcached
    container_name: memcached
    expose:
      - "11211"
    environment:
      MEMCACHED_MEMORY_LIMIT: 128
  webapp:
    container_name: webapp 
    build:
      context: ./build/nginxphp
    volumes:
      - ./www:/var/www
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - mariadb
      - memcached
  api:
    image: containous/whoami
    container_name: api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest    
    container_name: phpmyadmin
    depends_on: 
      - mariadb
    environment:
      PMA_HOST: ${DB_HOST}
      VIRTUAL_HOST: ${PHPMYADMIN_HOST}
  haproxy:
    container_name: haproxy
    build: 
      context: ./build/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 80:80
      - 8888:8888
