version: "3.6" 
services:
  nginx:
    container_name: hd-nginx
    build:
      context: ./nginx
    ports: 
      - "8400"
    volumes:
      - ./www:/var/www
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - fpm
      - memcached
      - elasticsearch
    environment:
      VIRTUAL_HOST: ${HOST}
  fpm:
    container_name: hd-php-fpm
    build: 
      context: ./fpm
    volumes:
      - ./www:/var/www
      - ./fpm/uploads.ini:/etc/php/5.6/fpm/conf.d/uploads.ini
    expose: 
      - "9000"
    depends_on:
      - ${DB_HOST}
      - memcached
      # - redis
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_NAME}
  db:
    image: mariadb:10.1.32
    container_name: hd-mariadb
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./var/lib/mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest    
    container_name: hd-phpmyadmin
    depends_on: 
      - db
    ports:
      - "2112:2112"
    environment:
      PMA_HOST: db
      VIRTUAL_HOST: ${PHPMYADMIN_HOST}
  memcached:
    image: memcached
    container_name: hd-memcached
    expose:
      - "11211"
    environment:
      MEMCACHED_MEMORY_LIMIT: 128
  elasticsearch:
    container_name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
    ports: 
      - "9200:9200"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # redis:
    # image: redis
    # ports: 
      # - "6379"
